export enum ActionType {
  ADD_TICKETS = 'ADD_TICKETS',
  SET_LOADING_STATE = 'SET_LOADING_STATE',
  SET_CURRENT_SORT = 'SET_CURRENT_SORT',
  TOGGLE_STOP = 'TOGGLE_STOP',
  TOGGLE_ALL_STOPS = 'TOGGLE_ALL_STOPS',
  SET_NEXT_OFFSET = 'SET_NEXT_OFFSET',
}
